# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-app--prod

commonLabels:
  app.kubernetes.io/environment: prod

commonAnnotations:
  'app.kubernetes.io/version': 'release-0.1'

configMapGenerator:
  - name: spring-cloud-config
    env: spring-cloud-config.env
    behavior: merge

bases:
  - ../common

resources:
  - namespace.yaml
