# Copyright 2018 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: petclinic

commonAnnotations:
  app.kubernetes.io/version: release-0.1.1

bases:
  - https://github.com/kitops/spring-cloud-config-platform/spring-cloud-netflix?ref=v1.0

resources:
  - admin-server/admin-server.yaml
  - customers-service/customers-service.yaml
  - vets-service/vets-service.yaml
  - visits-service/visits-service.yaml

images:
  - name: admin-server
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-admin-server
  - name: spring-cloud-netflix-api-gateway-image
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-api-gateway
  - name: spring-cloud-netflix-config-server-image
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-config-server
  - name: customers-service
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-customers-service
  - name: spring-cloud-netflix-discovery-server-image
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-discovery-server
  - name: spring-cloud-netflix-hystrix-dashboard-image
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-hystrix-dashboard
  - name: vets-service
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-vets-service
  - name: visits-service
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/petclinic-app/spring-petclinic-visits-service
  - name: grafana-server
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/grafana
  - name: prometheus-server
    newTag: release-0.1.1
    newName: gcr.io/protokit-238521/prometheus

vars:
  - name: ADMIN_SERVICE_NAME
    objref:
      kind: Service
      name: admin-server
      apiVersion: v1
  - name: CUSTOMERS_SERVICE_NAME
    objref:
      kind: Service
      name: customers-service
      apiVersion: v1
  - name: VETS_SERVICE_NAME
    objref:
      kind: Service
      name: vets-service
      apiVersion: v1
  - name: VISITS_SERVICE_NAME
    objref:
      kind: Service
      name: visits-service
      apiVersion: v1